import {
	AirplaneTiltIcon,
	BarbellIcon,
	BedIcon,
	BicycleIcon,
	BookOpenIcon,
	BoneIcon,
	BuildingsIcon,
	CarIcon,
	CoinsIcon,
	CoffeeIcon,
	CouchIcon,
	CookieIcon,
	FileTextIcon,
	FilmStripIcon,
	FirstAidIcon,
	ForkKnifeIcon,
	GasPumpIcon,
	GiftIcon,
	GraduationCapIcon,
	HandCoinsIcon,
	HandHeartIcon,
	HeartbeatIcon,
	HouseIcon,
	IceCreamIcon,
	LaptopIcon,
	LightningIcon,
	MapPinIcon,
	MicrophoneIcon,
	PaletteIcon,
	ParkIcon,
	PhoneIcon,
	PiggyBankIcon,
	PillIcon,
	PizzaIcon,
	QuestionIcon,
	ReceiptIcon,
	RepeatIcon,
	ScanIcon,
	ScissorsIcon,
	ScrollIcon,
	ShieldCheckIcon,
	ShieldIcon,
	ShoppingBagIcon,
	SmileyIcon,
	StethoscopeIcon,
	SuitcaseRollingIcon,
	TrainIcon,
	TShirtIcon,
	UmbrellaIcon,
	WalletIcon,
	WarningIcon,
	WrenchIcon,
	WifiHighIcon,
} from "@phosphor-icons/react";
import { ComponentProps } from "react";

const iconMapping: Record<
	string,
	React.ComponentType<ComponentProps<"svg">>
> = {
	BookOpen: BookOpenIcon,
	Zap: LightningIcon,
	Bed: BedIcon,
	Luggage: SuitcaseRollingIcon,
	ShieldCheck: ShieldCheckIcon,
	ParkingMeter: ParkIcon,
	House: HouseIcon,
	Bone: BoneIcon,
	ReceiptText: ReceiptIcon,
	Utensils: ForkKnifeIcon,
	Clapperboard: FilmStripIcon,
	Laptop: LaptopIcon,
	PiggyBank: PiggyBankIcon,
	Phone: PhoneIcon,
	Building2: BuildingsIcon,
	Stethoscope: StethoscopeIcon,
	HandCoins: HandCoinsIcon,
	TriangleAlert: WarningIcon,
	Bike: BicycleIcon,
	Shield: ShieldIcon,
	HeartHandshake: HandHeartIcon,
	BriefcaseMedical: FirstAidIcon,
	GraduationCap: GraduationCapIcon,
	Car: CarIcon,
	MapPin: MapPinIcon,
	Sofa: CouchIcon,
	ScanFace: ScanIcon,
	Fuel: GasPumpIcon,
	Scissors: ScissorsIcon,
	Wifi: WifiHighIcon,
	Coins: CoinsIcon,
	Pill: PillIcon,
	HeartPulse: HeartbeatIcon,
	Laugh: SmileyIcon,
	FileText: FileTextIcon,
	Umbrella: UmbrellaIcon,
	Pizza: PizzaIcon,
	Croissant: CookieIcon,
	IceCreamCone: IceCreamIcon,
	ShoppingBasket: ShoppingBagIcon,
	CircleHelp: QuestionIcon,
	Shirt: TShirtIcon,
	MicVocal: MicrophoneIcon,
	Wallet: WalletIcon,
	Dumbbell: BarbellIcon,
	Coffee: CoffeeIcon,
	Repeat: RepeatIcon,
	Plane: AirplaneTiltIcon,
	TrainFront: TrainIcon,
	Gift: GiftIcon,
	Palette: PaletteIcon,
	Wrench: WrenchIcon,
	Scroll: ScrollIcon,
};

export default function CategoryIcon({
	iconName,
	...props
}: ComponentProps<"svg"> & { iconName: string }) {
	const Icon = iconMapping[iconName];

	if (!Icon) {
		return <QuestionIcon {...props} />;
	}

	return <Icon {...props} />;
}
